
colleges = [
    ['St. Xaviers College', 'Maitighar', 'B.Sc. CSIT, Microbiology', 'M.Sc.Physics, Microbiology'],
    ['Mt.Annapurna Campus', 'Pokhara', 'B.Sc.CSIT, MB', ''],
    ['Birendra Memorial College', 'Dharan', 'B.Sc.MB, CSIT', ''],
    ['New Summit College', 'Purano Baneshwor', 'B.Sc.CSIT', ''],
    ['Kathford International College of Engineering and Management', 'Lalitpur', 'B.Sc.CSIT', ''],
    ['Prime College', 'Nayabazar, Khusibu', 'B.Sc.CSIT', ''],
    ['National College of Computer Studies', 'Kantipath', 'B.Sc. CSIT', ''],
    ['Nagarjun College of IT', 'Pulchowk', 'B.Sc.CSIT', ''],
    ['St. Lawrence College', 'Chabhil', 'B.Sc.CSIT', ''],
    ['Shreeyantra College', 'Damak, Jhapa', 'B.Sc.CSIT', ''],
    ['Orchid International College', 'Sinamangal', 'B.Sc.CSIT', ''],
    ['Nepalaya College', 'Kalanki', 'B.Sc.CSIT', ''],
    ['Madan Bhandari Memoral College', 'Anamnagar', 'B.Sc.CSIT', ''],
    ['Vedas College', 'Jawalakhal', 'B.Sc.CSIT', ''],
    ['Kathmandu Bernhardt College', 'Bafal', 'B.Sc.CSIT', ''],
    ['Academia Int. College', 'Gwarko', 'B.Sc.CSIT', ''],
    ['Asain School of Management & Technology', 'Samakhushi', 'B.Sc.CSIT', ''],
    ['Himalaya College Of Eng.', 'Shankhamul', 'B.Sc.CSIT', ''],
    ['Sagarmatha College Of Science & Technology', 'Sanepa', 'B.Sc.CSIT', ''],
    ['College Of Applied Business', 'Gangahity, Chabahil', 'B.Sc.CSIT', ''],
    ['Ambition College', 'Baneshwor', 'B.Sc.CSIT', ''],
    ['Texas International College', 'Chabahil', 'B.Sc.CSIT', ''],
    ['Deerwalk Ins. Of Technology', 'Sifal', 'B.Sc.CSIT', ''],
    ['NIST College', 'Banepa', 'B.Sc.General, CSIT', ''],
    ['National Infotec College', 'Birgung', 'B.Sc.CSIT', ''],
    ['Niharika College', 'Biratnagar', 'B.Sc.CSIT', ''],
    ['Birat Kchitize College', 'Biratnagar', 'B.Sc.CSIT', ''],
    ['Birat Multiple College', 'Biratnagar', 'B.Sc. (MB), CSIT B.Tech.(Food)', ''],
    ['AIMS College', 'Biratnagar', 'B.Sc. CSIT', ''],
    ['Godawari College', 'Itahari', 'B.Sc.CSIT', ''],
    ['Hetauda City College', 'Hetauda, Makawanpur', 'B.Sc.CSIT', ''],
    ['Indreni College', 'Bharatpur', 'B.Sc.CSIT', ''],
    ['Soch College Of I.T.', 'Pokhara', 'B.Sc.CSIT', ''],
    ['Lumbini ICT College', 'Gaidakot, Nawalparasi', 'B.Sc.CSIT', ''],
    ['Lumbini city College', 'Butawal', 'B.Sc.CSIT', ''],
    ['Trinity International College', 'Dillibazar, Kathmandu', 'B.Sc.CSIT', ''],
    ['Kathmandu College of Technology', 'Lokanthali, Bhaktapur', 'B.Sc.CSIT', ''],
    ['Swastik College', 'Thimi, Bhaktapur', 'B.Sc.CSIT', ''],
    ['Samridhi College', 'Lokanthali, Bhaktapur', 'B.Sc.CSIT', ''],
    ['Nepalgung Campus', 'Nepalgung', 'B.Sc.CSIT', ''],
    ['Nepathya College', 'Butawal', 'B.Sc.CSIT', ''],
    ['Ambikeshowri Information & Technical Campus', 'Ghorai, Dang', 'B.Sc.CSIT', ''],
    ['Bake Bageshori College', 'Nepalgung', 'B.Sc.CSIT', ''],
    ['Asian College Of Higher Studies', 'Kamaladi', 'B.Sc.CSIT', ''],
    ['Himalaya Darahan Colllege', 'Biratnagar', 'B.Sc.CSIT', '']
]
